# Complementing a Strand of DNA

def complement(s):
	reverse = ""
	complement = []
	for i in s:
		reverse = i + reverse
	for j in reverse:
		if j == "T":
			complement.append("A")
		elif j == "A":
			complement.append("T")
		elif j == "G":
			complement.append("C")
		else:
			complement.append("G")			
	print (''.join(complement))

complement("TAGTCAAAATTACGGTATGGCACAGAACTTTTCCCAACCCCAGGTGTTTATTCCGTAGGATTTGTACGGGGTACTAAGGAGCAATGGCATAGCGACGACTGCAATCTGGCTATCGTTATTGGGCATTAGGACTCACCACAATTCCGATATAAGCTTCGATTTGAATAAATGGAGATTATGGCTGTCGTTGAGATCGACAGTGAATGCACTTGTAGCAGGCCGCACGCTCATTCTTTGCGGTTTCCCCCACCCCACGCAATCATTGCTGAGAGCTACTGAAGATTGGTGTGGACTGAGTCCGATCACTATGTGGGGACATCTCGCTCATTGTTACACATAGGGCACATGTATAAGTGCAAGTCACAGCTATACAGGCCCGTTCTCGCCCCGTCAAACACAGACAGTCTCACTGCCTGCTGGTGGCCTTAACGTATACGGGAGGTGAGCACAATCAACGAGCTTAAACTACGTTCGTAAACGGCCGCGTTATGCGAATAGCACCCATACAGGTGTTTATCAGATACGCCAAGCAGCTCGTGGCTTAGTTGAGGCAACTCGGTAGAGCAGTAGTAAAACCAGACTCAGATTTCGCGTAGGTAGGTGTTAAGTATATTTTTAAGTCAAAGTAATTACCAAGATGAGCTTATAGAGCCTTTCCGCGTAAAGCACCGGGTAGGTTCGCTCATCGTTTTGCACTATACATTTAGTAGTAGCGCGCTTCCATCCCCGTAGGCGACTAAGAACGGTTGCTCGACGAGTATGCGGGACCGCCAACTGAATTATCTAAGTCATTATTCGCGCGTCTCAACAGGGTTAATTCATCCTATTGCTAGCACTGCACACATACGGATAAAGGACCCAGGGTCTGAATCAGGTGTCGTAATGTTCGCGCGTCAGCAGTTTGTCCGAGAA")