"""
Problem
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, 
then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.

"""

def complement(dna_string):
	"This function reverses the string, and then creates the complement"
	reverse = ""
	complement = []

	for letter in dna_string:
		reverse = letter + reverse

	for comp in reverse:
		if comp == "T":
			complement.append("A")
		elif comp == "A":
			complement.append("T")
		elif comp == "G":
			complement.append("C")
		else:
			complement.append("G")
						
	print (''.join(complement))

complement("TAGTCAAAATTACGGTATGGCACAGAACTTTTCCCAACCCCAGGTGTTTATTCCGTAGGATTTGTACGGGGTACTAAGGAGCAA"
	"TGGCATAGCGACGACTGCAATCTGGCTATCGTTATTGGGCATTAGGACTCACCACAATTCCGATATAAGCTTCGATTTGAATAAATGGAGAT"
	"TATGGCTGTCGTTGAGATCGACAGTGAATGCACTTGTAGCAGGCCGCACGCTCATTCTTTGCGGTTTCCCCCACCCCACGCAATCATTGCTG"
	"AGAGCTACTGAAGATTGGTGTGGACTGAGTCCGATCACTATGTGGGGACATCTCGCTCATTGTTACACATAGGGCACATGTATAAGTGCAAG"
	"TCACAGCTATACAGGCCCGTTCTCGCCCCGTCAAACACAGACAGTCTCACTGCCTGCTGGTGGCCTTAACGTATACGGGAGGTGAGCACAAT"
	"CAACGAGCTTAAACTACGTTCGTAAACGGCCGCGTTATGCGAATAGCACCCATACAGGTGTTTATCAGATACGCCAAGCAGCTCGTGGCTTA"
	"GTTGAGGCAACTCGGTAGAGCAGTAGTAAAACCAGACTCAGATTTCGCGTAGGTAGGTGTTAAGTATATTTTTAAGTCAAAGTAATTACCAA"
	"GATGAGCTTATAGAGCCTTTCCGCGTAAAGCACCGGGTAGGTTCGCTCATCGTTTTGCACTATACATTTAGTAGTAGCGCGCTTCCATCCCC"
	"GTAGGCGACTAAGAACGGTTGCTCGACGAGTATGCGGGACCGCCAACTGAATTATCTAAGTCATTATTCGCGCGTCTCAACAGGGTTAATTC"
	"ATCCTATTGCTAGCACTGCACACATACGGATAAAGGACCCAGGGTCTGAATCAGGTGTCGTAATGTTCGCGCGTCAGCAGTTTGTCCGAGAA")