"""
Find Motif

---------------

Using the regular expression library to find matching strings in a much longer string. 

Using the finditer function in the regular expression library makes this a simple exercise. 

The replace method cleans up the output, however there is an easier/cleaner way to do this I am sure. 

"""

import re

def findMotif(dna):
	locations = [(q.start() + 1) for q in re.finditer(('(?=CGCCCACCG)'), dna)]
	print (((str(locations).replace("[", "")).replace("]", "")).replace(",", ""))

findMotif("GGTGTCGCCCACCGCGCCCACACGACGCCCACACCGCCCACCGCCCACTCGCCCACCATCCCTCGCCCACTACGCCCACAACCGCCCACACGCCCACATACTCGCCCACAACGCCCACCGCCCACTGCGCCCACATCGCCCACTACGACTGATTAATCGCCCACAATACGCGCCCACACGCCCACAGCGCCCACCGCGCCCACTCGCCCACTACGCCCACATCGCCCACCGGGAGCTCCCGCCCACAAGCGCCCACGCCCCTGGCGCCCACCGCCCACTTCCGCCCACACGCCCACCGCCCACCGCCCACACGCCCACGCGCCCACTCGCGCCCACCGCCCACACGCCCACGATCCGCCCACCGCCCACCGCCCACTGCGCCCACCGTTAACGCCCACCGCCCACCGCCCACTCCCGCCCACCGTCCGCCCACTCGCCCACTCGCCCACTCCAAGCCGCCCACACCCGCCCACAATGGGGCGCCCACCACCCTGCAGCTAGATCGCCCACCGCCCACGTCGCCCACCGCCCACTCGCCCACTTCGCCCACTATCGCCCACGCGCCCACCCACGCCCACCGCCCACAAGCCGCCCACCGCCCACACGCCCACATGTTTACTCGCCCACACGCCCACCGCCCACTGACGCCCACCCGCCCACCGCCCACACGCCCACACCGCCCACCGCCCACCGCCCACGTTAGGGCGCCCACCGCCCACCGTTATACGCCCACCGCCCACCCGCCCACCGCCCACCGCCCACCACGCCCACAGCGCCCACTACGCCCACACCCGCCCACCGCCCACCCGGCGCCCACGCGCCCACCGTGCGCCCACCAATGCTCGCCCACCCGCCCACCCGCCCACCGCGCCCACAGCGCCCACCAGCGCCCACACGCCCACCGCCCACCGAAACGCACGCCCACTCGCCCAC")
